### ISSUE TITLE
入力は反応しているが判定がすべてMISSになる

### ISSUE THREAD

**Issue by DTXMania** [DTXMania/DTXMania2#125]
**バージョン等**
DTXMania2 058

**不具合の内容**
電子ドラムの入力は画面上、反応しているが、判定がスルーされる(全てミスになる)

**Comment by WhiteRoad46** [comment]
判定位置調整が0ms以外だと判定がスルーされるようです。
0msだと問題なく動作しました。
※キーボード入力も同様の現象が発生しています。

**Comment by DTXMania** [comment]
バグでした。
判定位置調整はミリ秒単位なのですが、これを秒単位の値として使用していました。
次回リリースで修正されます。
どうもすみません。
