### ISSUE TITLE
選択ノーツの一括音量変更機能の実装

### ISSUE THREAD

**Issue by DTXMania** [DTXMania/DTXMania2#126]
選択しているノーツの一括音量変更ができるようにする。

案1：
選択して上画像の上げ下げをクリックしたらその時の音量が設定される。（変更がかかるまでは前の値で、変更を加えた時に選択しているノーツ全てにその値が設定される）

**Comment by WhiteRoad46** [comment]
DTXCreatorの置換機能な感じで、絶対値変更と相対値変更が出来ると嬉しいです。
なので、置換ウィンドウの実装でキレイにいくような気がします。
