### ISSUE TITLE
[SSTFEditor]スプラッシュシンバルの配置が分かりづらい

### ISSUE THREAD

**Issue by WhiteRoad46** [DTXMania/DTXMania2#131]
RC側で設定出来るが、実際にノーツが流れてくる時はLC側なので、
それならLC側で設定させれば良いのでは？と思いました。
(RC側に用意している理由があれば教えて下さい。)

![2020-08-02_20h55_05](https://user-images.githubusercontent.com/52472295/89122512-9da97200-d502-11ea-9104-7e8a1ec66d62.png)

**Comment by DTXMania** [comment]
フォーマットの仕様として、Splash, China, Ride の３つには左右の概念がなく、どこに位置していてもよいことになっています。
そのため、SSTFEditor ではこれら３つをすべて右レーンに配置しています。

一方、DTXMania2 ではこれら３つの位置をオプション設定で 左 または 右に設定することができ、かつその初期値が「 Splashは左」であるため、上記のように表示されています。

SSTFEditor 側でもオプション設定で可変にするかとも思ったのですが、混乱しそうなのでなんとなく保留にしています……。

**Comment by WhiteRoad46** [comment]
DTXMania2で左右オプションが存在するようでしたら、SSTFEditor側で「Splash, China, Ride」レーンを作って同様のオプションも設けた方が分かりやすいと思いました。
※デフォルト設定値はDTXMania2と同じにしておく。

DTXMania2側で意図的に変更しているのであればオプションの存在を認識しているはずなので、SSTFEditor側にオプションを設けても、そこまで大きな混乱は無いかと思います。
(DTXMania2のオプションを参照するのも一つの手かもしれませんね)
