### ISSUE TITLE
起動ができません。

### ISSUE THREAD

**Issue by pikasan4649** [DTXMania/DTXMania2#135]
**バージョン等**
 Ver.0.871
**不具合の内容**
DTXmaniaGR.exeを開いたエラーが出てきて、下記にエラー内容を書きます。

・DTXMania.exe -  Assert Failure
Expressipn: [mscorlib recursive resource look up bug]
Description: Infinite recursion during resource look up within ms corlib. This may be a bug in mscorlib. or potentially in certain exten extensibility points such as assembly resolve event or CultureInfo names. Resources name: Word_At」と書いてあり意味は全くわからず、書き写しです。選択肢が中止、デバック、無視でした。

**Comment by DTXMania** [comment]
報告ありがとうございます。

エラーの内容は何となく分かるとしても、バージョン 0.871 というものがどれを差しているのか良く分からないです。
もし初代 DTXMania の Release 087 のことを差しているのであれば、2011年というかなり古い年代のものになってしまいます。

正しいバージョンは分かりますか？（ウィンドウのタイトル部分に書かれている文字でいいです）
また、その DTXMania をどこのサイトから入手されましたか？

**Comment by DTXMania** [comment]
0.871というのは、どうやら TJAPlayer2 for PC の Ver.2020032000 のようですね。
下記をご案内して、こちらではいったんこのissueをクローズしますね。

[kairera0467/TJAP2fPC](https://github.com/kairera0467/TJAP2fPC)
